apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rsenvcomp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-lsaq-tenant/rsenvapp/rsenvcomp@sha256:485924187a121e6db8896a03a13dc4c8d609629db4440c8263a9211f083d94a5
        name: my-java-quarkus
        resources: {}
status: {}
